### Create New Course

POST http://localhost:8080/courses/createNewCourse HTTP/1.1
content-type: application/json

 { 
  "courseId" : "15", 
  "courseName" : "c++", 
  "facultyName" : "Shweta", 
  "material" : "https://www.w3schools.com/html/html_css.asp",
  "recordings": "https://meet.google.com/woi-gjix-jsx",
  "startDate":"2020-01-01", 
  "endDate": "2022-01-02" 
}

### Get All Course 
GET http://localhost:8080/courses/list

### Delete Course By Id 
DELETE http://localhost:8080/courses/delete/37

### Get  Course 
GET http://localhost:8080/courses/getCourseById/28

### Update Course
PUT http://localhost:8080/courses/updateCourse HTTP/1.1 
content-type: application/json

{
   "courseId" : "27", 
  "courseName" : "Java", 
  "facultyName" : "shreya", 
  "material" : "https://www/html/html_css.asp",
  "recording": "https://meet.google.com/woi-gjix-jsx",
  "startDate":"2020-01-01", 
  "endDate": "2022-01-02"
}

### Get Course By Name 
GET http://localhost:8080/courses/name?courseName=RPA

