### Create New Question 
POST http://localhost:8080/questions/ HTTP/1.1 
content-type: application/json

{ "id" : 4, "studentName" : "Bhushan", "question" : "What is html?" }

### Get Question by Id 
GET http://localhost:8080/questions/69

### Get all Questions 
GET http://localhost:8080/questions HTTP/1.1

### Create New Answer 
POST http://localhost:8080/questions/answer/69
content-type: application/json

{
"answer": "Hyper-Text Markup Language"
}

### Update Answer

PUT http://localhost:8080/questions/answer/69 HTTP/1.1 
content-type: application/json

{
"answer" : "Hyper-Text Markup Language."
}

### Delete Answer By Id 
DELETE http://localhost:8080/questions/answer/110

### Delete Question By Id 
DELETE http://localhost:8080/questions/110

